### ISSUE TITLE
Update Nava Logo

### ISSUE THREAD

**Issue by sarahknoppA6** [DSCoalition/digitalservicescoalition.org#107]
Nava would like their logo updated on the site. File is attached.

![Nava Logotype Black V01 (2)](https://github.com/DSCoalition/digitalservicescoalition.org/assets/91201622/2f503f43-1e96-4fbb-a891-497831b05894)

**Comment by DanielMiller-agile6** [comment]
also updated agile six's logo, since we also went through a bit of a rebrand :). Let me know if these look ok:

![Screen Shot 2023-05-12 at 10 47 16 AM](https://github.com/DSCoalition/digitalservicescoalition.org/assets/54035677/49e99498-3d72-4374-bf67-939bbbc7dc64)

---

![Screen Shot 2023-05-12 at 10 47 23 AM](https://github.com/DSCoalition/digitalservicescoalition.org/assets/54035677/4a9f02a7-5793-4946-b585-42e32eed263e)
